### ISSUE TITLE
Undersøke død Loki i kjøremiljø-prod

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/okctl#1017]
Får ikke sett noen logger i Grafana.

Nina 19 Aug 2022
>Venter med denne til Julius er tilstede

**Comment by deifyed** [comment]
Oppgraderte K8s til 1.21 og okctl til 0.0.104. Tester for å se om dynamodb:DeleteTable fiksen fikser dette problemet også. Logging fungerer værtfall nå. 

Lager en reminder og dobbeltsjekker dette om en uke

**Comment by deifyed** [comment]
Sjekket og finner ingen antydninger til feil. 

Neste checkpoint blir da retention period går ut
