### ISSUE TITLE
Finne ut av OOM issue for barnehagepris

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/okctl#1019]
Barnehagepris opplevde at en av applikasjonene sine svarte 503. Etter litt undersøkelse fant vi ut at den ene noden ble drept grunnet negative helsesjekker, og helsesjekkene var negative fordi noden hadde gått tom for minne. Etter alt for lang tid løste problemet seg selv. Antall noder hadde blitt skalert opp og syk node hadde blitt byttet ut.

[Slack tråd](https://oslokommune.slack.com/archives/CV9EGL9UG/p1654685111711629?thread_ts=1654677947.350209&cid=CV9EGL9UG)
[Tidslinje](https://oslokommune.slack.com/archives/C03HJTPAS77/p1654756026474009)
[OOM reproduksjonseksperimenter](https://docs.google.com/spreadsheets/d/1HOKwQbvznr4SiDMkGFR3rnz1GisHyoAHN93z2JLNLnY/edit#gid=0)

---
Vi ble enige om følgende [ref](https://oslokommune.slack.com/archives/CV9EGL9UG/p1655377485070179?thread_ts=1654677947.350209&cid=CV9EGL9UG):
1. Vente på k8s upgrade for å få riktig konfigurasjon av autoscale groups
2. Ta i bruk overprovisionering for at Loki kjappere skal komme på igjen
3. Når Loki kjapt kommer på igjen, eksperimentere med konfig

[chunk_retain_period](https://github.com/grafana/loki/issues/613#issuecomment-496233850)
[http read/write timeout // parallelism](https://github.com/grafana/loki/issues/4015#issuecomment-1035506622)
Overprovisioning
[Cluster overprovisioning in Kubernetes](https://medium.com/scout24-engineering/cluster-overprovisiong-in-kubernetes-79433cb3ed0e))
[Kubernetes Cluster Over-Provisioning: Proactive App Scaling](https://www.linkedin.com/pulse/kubernetes-cluster-over-provisioning-proactive-app-ajit-vedpathak/)

---
### Checklist
- [x] Komme med anbefaling etter reproduksjon
- [x] Researche og vurdere justering av thresholds for oppskalering
- [x] Undersøke OOM problem med Loki
- [ ] Informer teamet om avgjørelse i møtet

**Comment by deifyed** [comment]
https://oslokommune.slack.com/archives/CV9EGL9UG/p1655377485070179?thread_ts=1654677947.350209&cid=CV9EGL9UG
