### ISSUE TITLE
delete cluster feiler pga RDS CloudFormation stack ikke vil slettes

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/okctl#1023]
Det virker som nightly feiler fordi den ikke får slettet RDS CFN stack. Stacken klager over at RDSOutgoing security groupen ikke kan slettes fordi den må disassosieres fra et network interface først. Klarer ikke helt å se at dette er noe vi har forårsaket

Yngvar 7 Jul 2022 
>Antakelig får dette også nightly til å feile
---
Håvard 2 Sep 2022
>CloudFormation stack fails: https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/stackinfo?filteringStatus=active&filteringText=&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aeu-west-1%3A853850742759%3Astack%2Fokctl-rdspostgres-okctl-nightly-nightlydb%2Fcae17850-277e-11ed-9f5d-02d05c00a183

>resource sg-052cf453a28849f96 has a dependent object

>pkg/cfn/components/securitygroup/securitygroup.go - func NewPostgresOutgoing() is created but dependent object looks like the incoming group: NewPostgresIncoming

**Comment by yngvark** [comment]
Av en eller annen grunn skjer ikke dette lengre. Nightly funker fint.
