### ISSUE TITLE
Fjern TLS 1.0 og 1.1 for ALB-er fra okctl apply application

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/okctl#1027]
Anbefalt tiltak fra EY.

Denne oppgaven går ut på å legge til dette i default oppsettet fra apply application.

Oppgraderingspath er å kjøre okctl apply application på nytt. Eller bare legge på 

```yaml
alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
```

i appens ingress.

Linker:
* https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html

**Comment by yngvark** [comment]
This was solved by #1003
