### ISSUE TITLE
[FEATURE] Documentation: argocd & docker images

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/okctl#169]
**Is your feature request related to a problem? Please describe.**
Coming into okctl for the first time, and to be able to get up and running quickly with argocd, there should be a best practice/introduction for setting up docker images and secrets.  

**Describe the solution you'd like**
A step by step describing how to use gihub or aws to store docker images, and how to set up keys and include them in the application yaml file so that argocd can get access to them.

**Comment by paulbes** [comment]
Also tracked via: https://trello.com/c/0O9tsMfi/156-improve-user-documentation
