### ISSUE TITLE
[FEATURE]Better documentation - visualize the cluster & application setup

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/okctl#170]
**Is your feature request related to a problem? Please describe.**
After running okctl and setting up a cluser & application I have no easy overview of what okctl is doing behind the scene when setting up clusters and applications

**Describe the solution you'd like**
A visual overview of what is being deploy: network, groups, connections, clusters etc. so that it is easy to get new people to understand the infrastructure being set up with okctl. Each version or major upgrade should have a corresponding visual representation of the infrastructure

**Comment by paulbes** [comment]
Also tracked via: https://trello.com/c/0O9tsMfi/156-improve-user-documentation

**Comment by paulbes** [comment]
I wonder if we should try to automate some of this 🤔 . We have several cloud formation templates that we generate and store in the `output` folder of the IAC repository. I see that there exist several tools for visualizing these templates. This doesn't solve all the problems, e.g., we still need to describe what we put inside the cluster.

Anyone have any experience with generating diagrams from cloud formation templates?

**Comment by deifyed** [comment]
I suggest a quick and easy fix by throwing something up in draw.io for now. We can explore automating it when core features are done. Whaddya say

**Comment by deifyed** [comment]
Something like [this](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=okctl-aws-resources.drawio#R7Vxbc5s4FP41nuk%2BJMPd9qPjuEkmaSZbt5u2bwooNh2MGCF82V9fCZC5yHZIySKly4uDDpIQ33d0dM6RyMCcrrZXGETLT8iDwcDQvO3AvBwYhu44Bv3DJLtMMhwOM8EC%2B15eqRDM%2FX9hLtRyaeJ7MK5UJAgFxI%2BqQheFIXRJRQYwRptqtWcUVJ8agQUUBHMXBKL00ffIMpOObK2QX0N%2FseRP1rX8zgrwyrkgXgIPbUoiczYwpxghkl2ttlMYMPA4Llm7j0fu7geGYUiaNDgLL%2FTJz9tx%2BPw02j2SbQi%2F%2FH2m5%2FTEZMffGHoUgLyIMFmiBQpBMCukFxgloQdZtxotFXXuEIqoUKfCn5CQXc4mSAiioiVZBfldOmK8%2B5a3TwvfWeHc5sXLbfnm5Y6Xtj75Vrr%2Bzvuj10UTVuAtRJBy3GKUYBeeQCZXUwLwApIT9YxRVpHBVnpCzsEVRCtIX4FWwDAAxF9X9Qrk6rnY19s3fUA%2BHbOh5VPJ5nqUTySdqyDvIhtp3qrQA3pRGkYhSrXjNZpiStGUVzP%2Bu7rVgaaM5WiK4XSrKTkeaxAk%2BSvMpqKZKVSD8blZ%2BgTOI5ACvaFLSVUNjpKzhpjA7Uk087vWqIZKXtwUVl3nsmXJotfBK%2BNfQe7VE8rpJ9QRZKyGM0ofdjSjJJteS5hRn1FCoC2a5K5nla7YpNo7W3Im1blhqzyvmq5U%2BpuvVO1IleOk%2FmGk8h4VIVUX3YSB4QT0DS48f00vF%2BzyAfsrkI7qGsWE0mloP1AIeU365FLlA%2B0%2FRBh5iUvOYLj2MQpXFN9zFAfoPN7R%2FlbxX7zRE653U%2B%2F8qKnVOjG1Tm0R0kVba2idOjDjJgxO8AJN6T3t602qWy7CXmP6qE4j1zunRbBiiKb3o0wnrn%2FsxZXmyhOpWzUmR9JXTb0Jk1O0CH1qJdnQXk1kQpZ%2FOI17L1EajXYfURxBxnEaLpK2%2FdaL5OGIYlRTnlFNJ7I3%2Bs8iCsfqNaWlpjjm%2F0JTeHrz9NJgbGmV2e2c%2FoaI5esFI%2F5hRWeWFjBU34%2FLVc%2BkjWVbeEN0ue4QYF7xBQhA6EIcKwea7shGzZQbPyps7UytobUz1QoezX79as3om69f7Rgd9oy2ZfTNfdd2jI56Rtsy6ijFqNVvAbdmVK3MutWvo20Z5eGZKozaPaNtGVXL17X6rF5rRg2lGOXjLkXx%2FzxMBZa73ss3VDshw4POEk46SzSlYGnpToQfI8oYzKiDa5BmzjDMVEd%2BLsS0FEsg8aivBOk8eQohUQ8rBfJGtgBWeu4mNTlPgYL6ZZjSMXMOz9mbkEBM9YxeXtEJuwE75cAzNengieldM82sByAmvstgfFBP6cyhbNwscUE9sEmRQnk%2F%2BUJ%2FF5kKxoruO9QRtizpCDc6IXDPEJ5M794LrvaBMzQd42oIuFoMxDl0E%2BwTNvYrilKkHnTSD63w4xZ9XCQoVdMjgZZi2agDXw6wPWXJcZFTO3knPS46cO671%2FyKQr98zkexHI%2Fo%2BKVe823ylHrNLNTQ3CCJqRMtfSkYatX5ID2otRs5Jx%2BpTmSpggijZz94xSHi5%2BjMg88gCcj7ObsyNKssHQqnx52y1O8HvnDo8GWr9ebfO7Vi1Ok9sNaMquWB8a%2F1e0Z%2Fm1FHLc%2FCFnOYaR7kAQW%2BKz8HNxqp5kuIMcjkkZ1rrZ2zlI7cWLljlrboxM62LOsLgsv7U2GcHMDk58od0W%2FlgM2hi1XYlKmDJj9H7og7WENm0D4jFTZk6vZMfm7cETdkbiafTgDVTVJlVPumXnpSxRENfxqCf42ZsdcihALp2qVrY8WWS2csgNI7jBkyebj7ssOoWFAnfvCz%2F%2FBTss3Qte4ysbRY%2FGuu7GOq4h%2BcmbNf) @haavardeide ?

**Comment by deifyed** [comment]
Or [this](https://deploy-preview-315--wonderful-knuth-0d954b.netlify.app/about/resources/)?
