### ISSUE TITLE
[BUG]okctl adduser: not able to use oslo.kommune.no address

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/okctl#173]
**Describe the bug**
Running `okctl adduser dev my.email@origo.oslo.kommune.no` results in `Error: UserEmail: must be a valid email address`

**To Reproduce**
Run `okctl adduser dev my.email@origo.oslo.kommune.no`

**Expected behavior**
I would expect that using origo.oslo.kommune.no address would be possible,using my `gmail.com` address works fine

**Comment by deifyed** [comment]
I'm unable to reproduce.

```~/origo/kjøremiljø/okctl-infrastructure (production:origohub) $ okctl adduser production my.email@origo.oslo.kommune.no
.   creating-identity-pool-users: identity-pool-user (elapsed: 31 seconds 305 microseconds)created identity-manager: identity-pool-user
storage operations:

	StoreStruct[preprocessing=json]: ipu-outputs.json (...lo-kommune-no/ipu-outputs.json)
	StoreBytes: ipu-cf.yaml (...go-oslo-kommune-no/ipu-cf.yaml)
	StateUpdate[add]: IdentityPoolUser (...my.email@origo.oslo.kommune.no)
	StoreStruct[preprocessing=yaml]: .okctl.yml (...kctl-infrastructure/.okctl.yml)

✓   creating-identity-pool-users
```

Seems this have been fixed. Are you still experiencing this @haavardeide ?
