### ISSUE TITLE
[BUG]Bad feedback to user when trying to apply application to non-existing environment

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/okctl#174]
**Describe the bug**
When trying to apply a application to a non-existing environment you get a error message that is cryptic: `Error: failed to authenticate with aws: no valid credentials: authenticator[0]: failed to populate required fields: AwsAccountID: cannot be blank`

**To Reproduce**
Only have `dev` environment set up and try to apply to `prod`: `okctl apply application prod -f application.yaml`

**Expected behavior**
A error message with a clearer text: `Cannot apply application to non-existing environment`

**Comment by deifyed** [comment]
Fixed in #261
