### ISSUE TITLE
[BUG]Better output message if gpg fails

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/okctl#175]
**Describe the bug**
Running okctl results in the output `gpg: dekryptering mislyktes: No secret key` without describing what this is and how to fix it.

**To Reproduce**
Running any okctl command will result in this output if nothing is set up (and there is no documentation as far as I can see on how I should set up pass for this to work)

**Comment by paulbes** [comment]
Also tracked via: https://trello.com/c/dHPxjOj7/108-improve-the-user-experience-around-the-keyring

**Comment by paulbes** [comment]
We have now fixed this with #314, the functionality has not been released yet, but it is on its way.
