### ISSUE TITLE
[BUG]okctl create application: overwrites existing application.yaml

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/okctl#192]
**Describe the bug**
If I have a existing `application.yaml` file in `./´ and run `okctl create application dev` then the checked-in application.yaml file is updated and replaced with boilerplate application.yaml content

**To Reproduce**
See description 

**Expected behavior**
If a application.yaml file exists I would either expect to get a prompt asking me to confirm that okctl can overwrite the content of the file, or that okctl bails out with a error message

could also be fixed with additional output parameter: `okctl create application dev --out application-api.yaml`

**Additional context**
If I have many applications in a git repo: what should be the best practice of storing application.yaml? In the root folder of the git repo or within the `infrastructure/base/application/my-application-name`

**Comment by deifyed** [comment]
Good point. I'll look into it.

For now, theres no need to persist the `application.yaml` file. It serves as a (in my opinion) simpler way to input the necessary data as an alternative to a gazillion cli flags or a cli wizard.

**Comment by deifyed** [comment]
Fixed in #264
