### ISSUE TITLE
[FEATURE] Consider replacing AWSALBIngressController with AWSLoadBalancerController 

### ISSUE THREAD

**Issue by bsek** [oslokommune/okctl#239]
We would like to use aws-load-balancer-type: "nlb-ip" which enables us to create network load balancers for use with pods running on Fargate nodes. This functionality is available in AWSLoadBalancerController but not in AWSALBIngressController.

As the new AWSLoadBalancerController is backwards compatible with the existing AWSALBIngressController, this should in theory not create any problems with the existing infrastructure but works as a simple replacement.

**Comment by paulbes** [comment]
Absolutely, this is on the roadmap, more a question of when than if 👍
